name: Docker Image CI

on:
  push:
    branches: 
      - $default-branch
      - development
      - master
    tags:
      - '*.*.*-*'
  # Run tests for any PRs
  pull_request:

env:
  IMAGE_NAME: jingo

jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          skip: .git
          check_filenames: true
          check_hidden: true
  super-linter:
    name: super-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v4.2.2
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs:
      - codespell
      - super-linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run:  docker build . --file Dockerfile --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" --tag ${IMAGE_NAME}
    - name: Compose up
      run: docker-compose -f .github/docker-compose.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker-compose -f .github/docker-compose.yml logs
    - name: Test the Docker image
      run: if ! [ "$(docker ps -a | grep "${IMAGE_NAME}" | head -1 | grep -c ${IMAGE_NAME})" = "1" ]; then exit 1; fi  
    - name: Compose down
      run: docker-compose -f .github/docker-compose.yml down
